[package]
name = "brainfuck-rust"
version = "0.1.0"
authors = ["Regentag <yeongtaek.ham@gmail.com>"]

[[bin]]
name = "bf"

# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
